name: Single Container Test
on: [push]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Test
      run: bash .github/workflows/single.sh
